function images = print_SCIRD(filters)
%print_SCIRD - prints the kernel filters
%
% Syntax: images = print_SCIRD(filters)
%
% Prints the kernel filters generated by SCIRD, by normalizing the values, to facilitate viewing

for filters_ind = 1:size(filters, 2)
    vector = filters{1, filters_ind}(:);
    dimension = size(filters{1, filters_ind}, 1);
    normalized = (vector - min(vector)) / (max(vector) - min(vector));
    images{filters_ind} = vec2mat(normalized, dimension);
end